executor: slurm
jobs: 25
use-apptainer: true
apptainer-prefix: /scratch.global/GDC/singularityimages
apptainer-args: "--bind /scratch.global,/projects,/spaces,/home"
software-deployment-method: [apptainer]
default-resources:
  slurm_account: gdc
  mem_mb: 4000
  runtime: 60
  plink_version: "plink/2.00-alpha-091019"
  bcftools_version: "bcftools/1.2"
  shapeit_version: "shapeit/4.2.2"
  rfmix_version: "rfmix/09599c1"
  samtools_version: "samtools/1.21"
latency-wait: 20
# Removed shared-fs-usage that was causing auto-mount issues
