import os 
import glob
from pathlib import Path
import pandas as pd


report: "../report/stylesheet.css"
configfile: "../config/config.yaml"
#validate(config, schema="../config/config.schema.yaml")

# Paths in include and configfile are relative to the Snakefile
# paths inside the rules are relative to where you run the command.

#CHROMOSOMES = range(1, 23)
CHROMOSOMES = range(20, 22)


# workflow.report_metadata.category_descriptions= {
#         "Initial QC": "../report/qc_intro.rst",
#         "Dimension reduction": "../report/dimensionReduction.rst",
#         "Ancestry Analysis": "../report/ancestry_intro.rst",
#         "Ancestry Specific QC": "../report/ancestrySpecificqc_intro.rst",
#     }

OUT_DIR = Path(config['OUT_DIR'])
REF = Path(config['REF'])

def get_ancestries(wildcards):
    # Wait for the PCArelate checkpoint and get the 'ancestry' output file
    ancestry_file = checkpoints.estimateAncestry.get(subset="full").output.ancestry
    return pd.read_csv(ancestry_file, sep="\t").pc_label.dropna().unique().tolist()


def get_ancestry_file(wildcards):
    """
    If the subset is 'full', return an empty list (no dependency).
    Otherwise, return the path to the estimated ancestry file.
    """
    if wildcards.subset == "full":
        return [] 
    else:
        return checkpoints.estimateAncestry.get(subset="full").output.ancestry
    


include: "rules/kgMeta.smk"
include: "rules/kgData.smk"
include: "rules/kgAssemble.smk"
include: "rules/Initial_QC.smk"
include: "rules/convertNfilt.smk"
include: "rules/Relatedness.smk"
include: "rules/Standard_QC.smk"
include: "rules/phase.smk"
include: "rules/PCAreference.smk"
include: "rules/umap.smk"
include: "rules/estimateAncestry.smk"
include: "rules/RFMIX.smk"
# include: "rules/trainGnomix.smk"


rule all:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "initialFilter_{CHR}.pgen", ANCESTRY=get_ancestries(wildcards), CHR = CHROMOSOMES),
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "initialFilter.bed", ANCESTRY= get_ancestries(wildcards)),
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "standardFilter.bed", ANCESTRY= get_ancestries(wildcards)),
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "unrelated.bed", ANCESTRY= get_ancestries(wildcards)),
        OUT_DIR / "full" / "standardFilter.bed",
        OUT_DIR / "full" / "unrelated.bed",

checkpoint assembleRef:
    input:
        REF / "1000G_highcoverage" / "population.txt",
        REF / "1000G_highcoverage" / "pedigree.txt",
        expand(REF / "1000G_highcoverage" / "1kGP_high_coverage_Illumina.chr{CHR}.filtered.SNV_INDEL_SV_phased_panel.vcf.gz", CHR = CHROMOSOMES),
        REF / "1000G_highcoverage" / "1000G_highCoveragephased.bed",

rule run_initialQC:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 60
    input:
        expand(OUT_DIR / "full" / "initialFilter_{CHR}.pgen", CHR=CHROMOSOMES),
        OUT_DIR / "full" / "standardFilter.pgen",
        OUT_DIR / "full" / "initialFilter.pgen",


rule run_estimateAncestry:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        OUT_DIR / "01-globalAncestry" / "sampleRefPCscores.sscore",
        OUT_DIR / "01-globalAncestry" / "umap_sample.csv",
        OUT_DIR / "01-globalAncestry" / "PC_referenceSpace.svg",
        OUT_DIR / "01-globalAncestry" / "latentDistantRelatedness.tsv",

rule run_ancestryQC:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "initialFilter_{CHR}.pgen", ANCESTRY= get_ancestries(wildcards), CHR = CHROMOSOMES),
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "initialFilter.pgen", ANCESTRY= get_ancestries(wildcards)),
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "standardFilter.pgen", ANCESTRY= get_ancestries(wildcards)),

rule run_relatedness:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        OUT_DIR / "full" / "unrelated.pgen",
        lambda wildcards: expand(OUT_DIR / "{ANCESTRY}" / "unrelated.pgen", ANCESTRY= get_ancestries(wildcards))

##### GOOD UP TO HERE

rule run_rfmix:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        expand(OUT_DIR / "02-localAncestry" / "chr{CHR}.phased.vcf.gz", CHR=CHROMOSOMES),
        expand(OUT_DIR / "02-localAncestry" / "chr{CHR}.lai.msp.tsv", CHR=CHROMOSOMES)


rule run_train_gnomix:
    threads: 1
    resources:
        nodes = 1,
        mem_mb = 4000,
        runtime = 420 # 1 week
    input:
        expand(f"{config['OUT_DIR']}/03-localAncestry/chr{{CHR}}_ancestry_gnomix", CHR=CHROMOSOMES),
