import os
import glob
from pathlib import Path
import pandas as pd
from snakemake.utils import validate


report: "../report/stylesheet.css"

# Paths in include and configfile are relative to the Snakefile
# paths inside the rules are relative to where you run the command.

CHROMOSOMES = config.get("chromosomes", list(range(1, 23)))

def input_is_per_chromosome():
    return "{CHR}" in config.get("INPUT", "")

OUT_DIR = Path(config.get("OUT_DIR", "/path/to/out"))
REF = Path(config.get("REF", "/path/to/ref"))
STORAGE_PREFIX = Path(os.path.abspath(config.get("local-storage-prefix", "/tmp")))
ANCESTRY_MODEL = config.get("ancestry", {}).get("model", "pca")

SCRIPTS_DIR = (Path(workflow.basedir) / "scripts").resolve()

ruleorder: convertPgenToVcf > compressAndIndexVcf
ruleorder: createProvidedAncestryKeepFiles > classifySamplesByAncestry


# report_metadata.category_descriptions= {
#         "Initial QC": "../report/qc_intro.rst",
#         "Dimension reduction": "../report/dimensionReduction.rst",
#         "Ancestry Analysis": "../report/ancestry_intro.rst",
#         "Ancestry Specific QC": "../report/ancestrySpecificqc_intro.rst",
#     }



include: "rules/common.smk"
include: "rules/kgMeta.smk"
include: "rules/kgAssemble.smk"
include: "rules/kgData.smk"
include: "rules/plotMissingness.smk"
include: "rules/convertPlink.smk"
include: "rules/Initial_QC.smk"
include: "rules/Relatedness.smk"
include: "rules/Standard_QC.smk"
include: "rules/phase.smk"
include: "rules/PCAreference.smk"
include: "rules/PCAinternal.smk"
include: "rules/umap.smk"
include: "rules/classifyAncestry.smk"
include: "rules/RFMIX.smk"
include: "rules/plotKaryotypeAncestry.smk"
# include: "rules/simulatePhenotype.smk"
if config.get("phenotypeSimulation", {}).get("enabled", False):
    include: "rules/simulatePhenotype2.smk"
include: "rules/snpHerit.smk"
include: "rules/preparePRSInputs.smk"
include: "rules/prsPipelines.smk"

rule all:
    input:
        expand(
            OUT_DIR / "01-globalAncestry" / "keep_{ANC}.txt", ANC=get_provided_ancestries()
        ) if has_provided_ancestry() else [],
        lambda wildcards: (
            [OUT_DIR / "01-globalAncestry" / "refRefPCscores.sscore",
             OUT_DIR / "01-globalAncestry" / "sampleRefPCscores.sscore",
             OUT_DIR / "01-globalAncestry" / "umap_sample.csv",
             OUT_DIR / "01-globalAncestry" / "umap_ref.csv",
             OUT_DIR / "01-globalAncestry" / "ancestry_classifications.tsv"]
            if not has_provided_ancestry() else []
        ),
        lambda wildcards: (
            [OUT_DIR / "02-localAncestry" / "ancestry_full.txt",
             expand(OUT_DIR / "02-localAncestry" / "chr{CHR}.lai.msp.tsv", CHR=LOCAL_ANCESTRY_CHROMOSOMES)]
            if (not has_provided_ancestry() and uses_rfmix()) else []
        ),
        expand(
            OUT_DIR / "{ANC}" / "initialFilter.pgen", ANC=get_provided_ancestries()
        ) if has_provided_ancestry() else (
            expand(OUT_DIR / "full" / "initialFilter.pgen")
        ),
        expand(
            OUT_DIR / "{ANC}" / "standardFilter.pgen", ANC=get_provided_ancestries()
        ) if has_provided_ancestry() else (
            expand(OUT_DIR / "full" / "standardFilter.pgen")
        ),
        # snpHeritability estimates
        lambda wildcards: (
            expand(
                OUT_DIR / "{subset}" / "03-snpHeritability" / "mash_output.csv",
                subset=get_ancestries(wildcards),
            )
            if config.get("snpHerit", {}).get("pheno") and config.get("snpHerit", {}).get("covar")
            else []
        ),


ruleorder: convertPlinkPerChromosome > convertPlinkSingleFile > mergeChromosomesAndFilter
ruleorder: convertPgenToVcf > compressAndIndexVcf

# include: "rules/trainGnomix.smk"


##### GOOD UP TO HERE
rule assembleRef:
    input:
        ancient(REF / "1000G_highcoverage" / "population.txt"),
        ancient(REF / "1000G_highcoverage" / "pedigree.txt"),
        ancient(expand(
            REF
            / "1000G_highcoverage"
            / "1kGP_high_coverage_Illumina.chr{CHR}.filtered.SNV_INDEL_SV_phased_panel.vcf.gz",
            CHR=range(1, 23),
        )),
        ancient(REF / "1000G_highcoverage" / "1000G_highCoveragephased.pgen"),
        ancient(expand(REF / "gmaps" / "hg38map.chr{CHR}.txt", CHR=range(1, 23))),


rule run_initialQC:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=60,
    input:
        lambda wildcards: (
            expand(OUT_DIR / "full" / "initialFilter_{CHR}.pgen", CHR=CHROMOSOMES)
            if "{CHR}" in config.get("INPUT", "")
            else [OUT_DIR / "full" / "initialFilter.pgen"]
        ),
        OUT_DIR / "full" / "standardFilter.pgen",
        OUT_DIR / "full" / "figures" / "smiss.svg",
        OUT_DIR / "full" / "figures" / "vmiss.svg",


rule run_pca:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,  # 1 week
    input:
        labels=ancient(REF / "1000G_highcoverage" / "population.txt"),
        eigen_ref=OUT_DIR / "01-globalAncestry" / "refRefPCscores.sscore",
        eigen_sample=OUT_DIR / "01-globalAncestry" / "sampleRefPCscores.sscore",


rule run_estimateAdmixing:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        labels=ancient(REF / "1000G_highcoverage" / "population.txt"),
        eigen_ref=OUT_DIR / "01-globalAncestry" / "refRefPCscores.sscore",
        eigen_sample=OUT_DIR / "01-globalAncestry" / "sampleRefPCscores.sscore",
        umap_ref=OUT_DIR / "01-globalAncestry" / "umap_ref.csv",
        umap_sample=OUT_DIR / "01-globalAncestry" / "umap_sample.csv",
        rfmix_global=lambda wildcards: OUT_DIR / "02-localAncestry" / "ancestry_full.txt" if uses_rfmix() else [],


rule run_classifyAncestry:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        rfmix=lambda wildcards: OUT_DIR / "02-localAncestry" / "ancestry_full.txt" if uses_rfmix() else [],
        posterior=OUT_DIR / "01-globalAncestry" / "posterior_probabilities.tsv",
        ridge_plot=OUT_DIR / "01-globalAncestry" / f"posterior_probability_stacked_{ANCESTRY_MODEL}.svg",


rule run_ancestryQC:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,  # 1 week
    input:
        lambda wildcards: (
            expand(
                OUT_DIR / "{ANCESTRY}" / "initialFilter_{CHR}.pgen",
                ANCESTRY=get_ancestries(wildcards),
                CHR=CHROMOSOMES,
            )
            if INPUT_IS_PER_CHROMOSOME
            else expand(
                OUT_DIR / "{ANCESTRY}" / "initialFilter.pgen",
                ANCESTRY=get_ancestries(wildcards),
            )
        ),
        lambda wildcards: expand(
            OUT_DIR / "{ANCESTRY}" / "standardFilter.pgen",
            ANCESTRY=get_ancestries(wildcards),
        ),


rule run_relatedness:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,  # 1 week
    input:
        OUT_DIR / "full" / "unrelated.pgen",
        lambda wildcards: expand(
            OUT_DIR / "{ANCESTRY}" / "unrelated.pgen",
            ANCESTRY=get_ancestries(wildcards),
        ),


rule run_rfmix:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        lambda wildcards: (
            expand(OUT_DIR / "02-localAncestry" / "chr{CHR}.phased.vcf.gz", CHR=LOCAL_ANCESTRY_CHROMOSOMES) +
            expand(OUT_DIR / "02-localAncestry" / "chr{CHR}.lai.msp.tsv", CHR=LOCAL_ANCESTRY_CHROMOSOMES)
        ) if uses_rfmix() else [],


rule run_simulatePhenotype:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        lambda wildcards: expand(
            OUT_DIR
            / "simulations"
            / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
            / "{anc}_simulation_pheno1.pheno",
            anc=config.get("phenotypeSimulation", {}).get("ancestries", ["AFR", "EUR"]),
        ),
        lambda wildcards: expand(
            OUT_DIR
            / "simulations"
            / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
            / "{anc}_simulation.eigenvec",
            anc=config.get("phenotypeSimulation", {}).get("ancestries", ["AFR", "EUR"]),
        ),
        lambda wildcards: expand(
            OUT_DIR
            / "simulations"
            / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
            / "{anc}_simulation.grm.bin",
            anc=config.get("phenotypeSimulation", {}).get("ancestries", ["AFR", "EUR"]),
        ),
        lambda wildcards: expand(
            OUT_DIR
            / "simulations"
            / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
            / "{anc}_simulation.grm.id",
            anc=config.get("phenotypeSimulation", {}).get("ancestries", ["AFR", "EUR"]),
        ),
        lambda wildcards: expand(
            OUT_DIR
            / "simulations"
            / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
            / "{anc}_simulation.grm.N.bin",
            anc=config.get("phenotypeSimulation", {}).get("ancestries", ["AFR", "EUR"]),
        ),



rule run_snpHerit:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        lambda wildcards: (
            expand(
                OUT_DIR
                / "{subset}"
                / "03-snpHeritability"
                / "mash_output.csv",
                subset=get_ancestries(wildcards),
            )
            if config.get("snpHerit", {}).get("pheno") and config.get("snpHerit", {}).get("covar")
            else []
        ),


rule run_PCAinternal:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        pcaobj=OUT_DIR / "full" / "pcair_pcaobj.RDS",
        pcrelate=OUT_DIR / "full" / "pcrelate_kinship.RDS",
        plot=OUT_DIR / "full" / "figures" / "pcair_pcs.svg",
        coords=OUT_DIR / "full" / "pcair_coordinates.tsv",


rule run_preparePRSInputs:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        Path(
            config.get("prsPipeline", {}).get(
                "generated_input_dir",
                str(
                    OUT_DIR
                    / "prs_inputs"
                    / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
                ),
            )
        )
        / "prs_inputs.env",


rule run_singleAncestryPRS:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        Path(
            config.get("prsPipeline", {}).get(
                "generated_input_dir",
                str(
                    OUT_DIR
                    / "prs_inputs"
                    / f"{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[1]}"
                ),
            )
        )
        / f"single_ancestry_{config.get('phenotypeSimulation', {}).get('ancestries', ['AFR', 'EUR'])[0]}.done",


rule run_singleAncestryPRSPipelines:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        PRS_METHOD_RUN_DIR / "single_ct.done",
        PRS_METHOD_RUN_DIR / "single_prsice.done",
        PRS_METHOD_RUN_DIR / "single_prscs.done",
        PRS_METHOD_RUN_DIR / "single_ldpred2.done",
        PRS_METHOD_RUN_DIR / "single_lassosum2.done",


rule run_multiAncestryPRSPipelines:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        PRS_METHOD_RUN_DIR / "multi_ctsleb.done",
        PRS_METHOD_RUN_DIR / "multi_prscsx.done",
        PRS_METHOD_RUN_DIR / "multi_ldpred2.done",
        PRS_METHOD_RUN_DIR / "multi_prosper.done",
        PRS_METHOD_RUN_DIR / "multi_sdprs.done",


rule run_allPRSPipelines:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        PRS_METHOD_RUN_DIR / "single_ct.done",
        PRS_METHOD_RUN_DIR / "single_prsice.done",
        PRS_METHOD_RUN_DIR / "single_prscs.done",
        PRS_METHOD_RUN_DIR / "single_ldpred2.done",
        PRS_METHOD_RUN_DIR / "single_lassosum2.done",
        PRS_METHOD_RUN_DIR / "multi_ctsleb.done",
        PRS_METHOD_RUN_DIR / "multi_prscsx.done",
        PRS_METHOD_RUN_DIR / "multi_ldpred2.done",
        PRS_METHOD_RUN_DIR / "multi_prosper.done",
        PRS_METHOD_RUN_DIR / "multi_sdprs.done",


rule runSingleAncestryPrecise:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,
    input:
        PRS_METHOD_RUN_DIR / "single_prsice.done",


##### GOOD UP TO HERE


rule run_train_gnomix:
    threads: 1
    resources:
        nodes=1,
        mem_mb=4000,
        runtime=420,  # 1 week
    input:
        expand(
            f"{config.get('OUT_DIR', '/path/to/out')}/03-localAncestry/chr{{CHR}}_ancestry_gnomix",
            CHR=LOCAL_ANCESTRY_CHROMOSOMES,
        ),
