extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  comments-indentation: disable
  empty-lines:
    max: 2
  comments:
    min-spaces-from-content: 1
  indentation:
    spaces: 2
    indent-sequences: consistent

ignore:
  - .snakemake/
  - .github/
  - docs/_build/
  - envs/*.def