#!/bin/bash -l
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=10
#SBATCH --mem=30GB
#SBATCH --time=1:00:00
#SBATCH -p agsmall
#SBATCH -o QC.out
#SBATCH -e QC.err
#SBATCH --job-name QC

source /projects/standard/gdc/public/envs/load_miniconda3-2.sh
conda activate gdcPipeline

WORK=$1
NAME=$2
REF=$3
path_to_repo=$4
OUTDIR=$5
CHECK_SEX=false

cd $WORK
mkdir -p $OUTDIR
cd $OUTDIR

plink --bfile ${WORK}/relatedness/study.${NAME}.unrelated --missing --out ${WORK}/relatedness/study.${NAME}.unrelated
# Marker missingness initial filter
plink --bfile ${WORK}/relatedness/study.${NAME}.unrelated --geno 0.1 --make-bed --out QC1

# Sample missingness initial filter
plink --bfile QC1 --mind 0.1 --make-bed --out QC2

# Marker missingness final filter 
plink --bfile QC2 --geno 0.02 --make-bed --out QC3

# Sample missingness final filter
plink --bfile QC3 --mind 0.02 --make-bed --out QC4

# Gender check:
if $CHECK_SEX ; then
  plink --bfile QC4 --check-sex
  grep 'PROBLEM' plink.sexcheck| awk '{print$1,$2}'> sex_discrepancy.txt
  plink --bfile QC4 --remove sex_discrepancy.txt --make-bed --out QC5
else
  mv QC4.bed QC5.bed
  mv QC4.bim QC5.bim
  mv QC4.fam QC5.fam
fi

# Minor allele frequency filter
plink --bfile QC5 --freq --out MAF_check
plink --bfile QC5 --maf 0.01 --make-bed --out QC6

# Hardy-Weinberg equilibrium check
plink --bfile QC6 --hardy --out plink
awk '{ if ($9 <0.00001) print $0 }' plink.hwe>plinkzoomhwe.hwe
plink --bfile QC6 --hwe 1e-6 --make-bed --out QC7a
plink --bfile QC7a --hwe 1e-10 --hwe-all --make-bed --out QC7

# Heterozygosity check:
plink --bfile QC7 --exclude $REF/inversion.txt --range --indep-pairwise 50 5 0.2 --out indepSNP
plink --bfile QC7 --extract indepSNP.prune.in --het --out R_check

# This is should be cleaned up
Rscript --no-save $path_to_repo/src/heterozygosity_outliers_list.R
sed 's/"// g' fail-het-qc.txt | awk '{print$1, $2}'> het_fail_ind.txt 
# plink --bfile $OUTDIR.QC7 --remove het_fail_ind.txt --make-bed --out $OUTDIR.QC8
plink --bfile QC7 --make-bed --out QC8

# Extract snps retained in $OUTDIR.QC8
plink --bfile QC8 --write-snplist --out QC8
plink --bfile ${WORK}/relatedness/study.${NAME}.related --extract QC8.snplist --make-bed --out study.${NAME}.related.QC8snps
cd $WORK

