flowchart TB
    input(1 Subjects 2 SNPs)
    filt("MAF > 0.05, (7)  SNP Missingness < 0.05 (8)  Subj Missing >0.05, (9)")
    joinedData(5 Subjects  6 SNPs)
    input --> filt
    filt --> joinedData
