flowchart TB
    input(1 Subjects 2 SNPs)
    filt("MAF > 0.05, (3)  SNP Missingness < 0.05 (4)  Subj Missing >0.05, (5)")
    joinedData(6 Subjects  7 SNPs)
    input --> filt
    filt --> joinedData
