executor: slurm
jobs: 25
software-deployment-method: [env-modules, apptainer]
software-deployment-prefix: "/path/to/your/storage/apptainer_images"
apptainer-prefix: "/path/to/your/storage/apptainer_images"
apptainer-args: "--bind /scratch.global,/projects,/spaces,/home"
default-resources:
  - slurm_account=gdc
  - mem_mb=4000
  - runtime=60
latency-wait: 20
