executor: slurm
jobs: 25
software-deployment-method: [env-modules, apptainer]
software-deployment-prefix: "/path/to/your/storage/apptainer_images"
apptainer-prefix: "/path/to/your/storage/apptainer_images"
apptainer-args: "--bind /scratch.global,/projects,/spaces,/home"
default-resources:
  - slurm_account=gdc
  - mem_mb=4000
  - runtime=60
  - plink_version: "plink/2.00-alpha-091019"
  - bcftools_version: "bcftools/1.2"
  - shapeit_version: "shapeit/4.2.2"
  - rfmix_version: "rfmix/09599c1"
  - samtools_version: "samtools/1.21"
latency-wait: 20
