---
title: DAG
---
flowchart TB
	id0[kgMeta]
	id1[download1000GenomesVcf - CHR: 1]
	id2[download1000GenomesVcf - CHR: 2]
	id3[download1000GenomesVcf - CHR: 3]
	id4[download1000GenomesVcf - CHR: 4]
	id5[download1000GenomesVcf - CHR: 5]
	id6[download1000GenomesVcf - CHR: 6]
	id7[download1000GenomesVcf - CHR: 7]
	id8[download1000GenomesVcf - CHR: 8]
	id9[download1000GenomesVcf - CHR: 9]
	id10[download1000GenomesVcf - CHR: 10]
	id11[download1000GenomesVcf - CHR: 11]
	id12[download1000GenomesVcf - CHR: 12]
	id13[download1000GenomesVcf - CHR: 13]
	id14[download1000GenomesVcf - CHR: 14]
	id15[download1000GenomesVcf - CHR: 15]
	id16[download1000GenomesVcf - CHR: 16]
	id17[download1000GenomesVcf - CHR: 17]
	id18[download1000GenomesVcf - CHR: 18]
	id19[download1000GenomesVcf - CHR: 19]
	id20[download1000GenomesVcf - CHR: 20]
	id21[download1000GenomesVcf - CHR: 21]
	id22[download1000GenomesVcf - CHR: 22]
	id23[assemble1000GenomesReference]
	id24[assembleRef]
	style id0 fill:#57D95F,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id1 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id2 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id3 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id4 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id5 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id6 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id7 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id8 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id9 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id10 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id11 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id12 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id13 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id14 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id15 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id16 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id17 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id18 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id19 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id20 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id21 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id22 fill:#5FD957,stroke-width:2px,color:#333333,stroke-dasharray: 5 5
	style id23 fill:#7ED957,stroke-width:2px,color:#333333
	style id24 fill:#57C5D9,stroke-width:2px,color:#333333
	id0 --> id1
	id0 --> id2
	id0 --> id3
	id0 --> id4
	id0 --> id5
	id0 --> id6
	id0 --> id7
	id0 --> id8
	id0 --> id9
	id0 --> id10
	id0 --> id11
	id0 --> id12
	id0 --> id13
	id0 --> id14
	id0 --> id15
	id0 --> id16
	id0 --> id17
	id0 --> id18
	id0 --> id19
	id0 --> id20
	id0 --> id21
	id0 --> id22
	id0 --> id23
	id1 --> id23
	id2 --> id23
	id3 --> id23
	id4 --> id23
	id5 --> id23
	id6 --> id23
	id7 --> id23
	id8 --> id23
	id9 --> id23
	id10 --> id23
	id11 --> id23
	id12 --> id23
	id13 --> id23
	id14 --> id23
	id15 --> id23
	id16 --> id23
	id17 --> id23
	id18 --> id23
	id19 --> id23
	id20 --> id23
	id21 --> id23
	id22 --> id23
	id23 --> id24
