---
title: DAG
---
flowchart TB
	id0[run_initialQC]
	id1[kgMeta]
	id2[Standard_QC]
	id3[convertNfilt]
	id4[initialFilter]
	style id0 fill:#57D5D9,stroke-width:2px,color:#333333
	style id1 fill:#57D95F,stroke-width:2px,color:#333333
	style id2 fill:#D9A657,stroke-width:2px,color:#333333
	style id3 fill:#ADD957,stroke-width:2px,color:#333333
	style id4 fill:#7ED957,stroke-width:2px,color:#333333
	id2 --> id0
	id3 --> id0
	id4 --> id0
	id4 --> id2
	id1 --> id3
	id1 --> id4
	id3 --> id4
